[general]
# benchmark name
name = 'Front-end Field Binding Dataset for Code Generation'
# select the most applicable category from the list provided by this repo
category = 'AI'
# mark your benchmark with custom tags (your own custom tags OR use existing from other projects)
tags = ['AI', 'code generation']

[info]
# programming language
language = 'language independent'
# license used in the project from the list provided by this repo
license = 'CC BY-NC 4.0'
# number of tests/cases/scenarios/benchmarks (should not be 0)
scenarios_num = 2300
# free text with a small desciption of the benchmark
description = 'Front-end Field Binding Dataset is a dataset used to automatically generate corresponding code snippet based on natural language description, in the actual front-end development work.'

[links]
# the link to the home page of the benchmark
homepage = 'https://tianchi.aliyun.com/dataset/dataDetail?dataId=107819'
# the link to the source code
sources = 'https://jupter-oss.oss-cn-hangzhou.aliyuncs.com/file/opensearch/documents/107819/data.zip'
# the link to the page with documentation
documentation = 'https://tianchi.aliyun.com/dataset/dataDetail?dataId=107819'
