[general]
# benchmark name
name = 'Datasets and Benchmarks to Explore Code Retrieval Using Natural Language.'
# select the most applicable category from the list provided by this repo
category = 'AI'
# mark your benchmark with custom tags (your own custom tags OR use existing from other projects)
tags = ['Code Retrieval', 'CodeSearchNet', "Code Representation"]

[info]
# programming language
language = 'python/java/go/php/javascript/ruby'
# license used in the project from the list provided by this repo
license = 'MIT'
# number of tests/cases/scenarios/benchmarks (should not be 0)
scenarios_num = 2000000
# free text with a small desciption of the benchmark
description = 'Datasets, tools, and benchmarks for representation learning of code.'

[links]
# the link to the home page of the benchmark
homepage = 'https://github.com/github/CodeSearchNet'
# the link to the source code
sources = 'https://s3.amazonaws.com/code-search-net/CodeSearchNet/v2/{python,java,go,php,javascript,ruby}.zip'
# the link to the page with documentation
documentation = 'https://github.com/github/CodeSearchNet#introduction'
