name: Build and test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build_and_test_with_code_coverage:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      # actions/checkout v1.* is needed for correct codecov upload, see https://github.com/actions/checkout/issues/237 for details
      - uses: actions/checkout@v1
      # ensure that gradle wrapper files in repository are valid by checking checksums
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-konan
          restore-keys: |
            ${{ runner.os }}-gradle-konan
      - name: Build with Gradle
        run: ./gradlew build

